version: '3'
services:
  activemq:
    image: webcenter/activemq:5.14.3
    environment:
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"
    ports:
    - "8161:8161"
  sign-up:
    build:
      context: ./sign-up
    links:
      - activemq
    ports:
    - "8080:8080"
  sign-in:
    build:
      context: ./sign-in
    links:
      - activemq
    ports:
      - "8081:8080"
  product-listening:
    build:
      context: ./product-listening
    ports:
    - "8082:8080"
